name: 'sigma-env'
channels:
  - defaults
  - bioconda
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - snakemake
  - tqdm
  - pip
  - pip:
    - pomegranate
    